spring.application.name=Email_Project

server.servlet.context-path=/email
server.port=8006

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 이메일 전송 관련 설정
# SMTP 서버 설정(gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=siteblod@gmail.com
spring.mail.password=krog fkkm itfh lndt
# > 2차 인증용 비밀번호(구글 앱 비밀번호에서 별도 생성 필요)

# 프로토콜 / 인코딩 설정
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

# 보안 설정
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true